### ISSUE TITLE
Remove default adding of `npm test` in pre-commit upon `npx husky-init` command

### ISSUE THREAD

**Issue by riboney** [typicode/husky-init#1]
**Issue:**
It seems that `husky-init` adds `npm test` to pre-commit hooks. This requires people to have to manually remove it if they don't have `test` script in their `package.json`

**Info**
  - I run this npm script: `"setup:husky": "npx husky install && npm install && npx husky add .husky/pre-commit 'npx lint-staged'"`
 
   - after command execution, my pre-commit file looks like:
   
![image](https://user-images.githubusercontent.com/14286113/146783328-f38f8684-660b-47f5-aac9-3911ff98f603.png)

   - Upon git commits I get this error:
   
![image](https://user-images.githubusercontent.com/14286113/146783205-09757c9b-4615-430f-a9c6-685c594445b9.png)

** EDIT**

proposal: Maybe prompt user if they wish the default option or wish to override it?

**Comment by typicode** [comment]
You can also use `husky set .husky/pre-commit '...'`. It will replace file content instead of adding to it.
I think it's better to have some default value (here `npm test`). Also I'd prefer not to make this project more customizable for now and keep it simple.

Thanks for the feedback :+1: :)

**Comment by leonhma** [comment]
can i just say that the default is quite annoying. totally agree with op
