### ISSUE TITLE
Adding husky to devDependencies should respect alphabetical order

### ISSUE THREAD

**Issue by elias-pap** [typicode/husky-init#5]
### Current behavior
When `"husky"` is added to `devDependencies` in `package.json`, it is simply appended at the end.
### Expected behavior
`"husky"` should be added to the correct place respecting alphabetical order of `devDependencies` keys, like package managers do.

**Comment by typicode** [comment]
That's a good point :+1:   `husky-init` will be replaced/deprecated soon so I'm going to close the issue.
